server:
  port: 8090
  forward-headers-strategy: framework
#  ssl:
#    enabled: true
#    key-store: classpath:cert.p12
#    key-store-password: B1t0n3!.II6
#    key-store-type: PKCS12
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: services
              uri: ${BACKEND_URL:http://localhost:8080}
              predicates:
                - Path=/services/api/**
              filters:
                - AddRequestHeader=Origin, http://localhost:4200

            - id: app-assets
              uri: ${APP_URL:http://localhost:8080}
              predicates:
                - Path=/assets/**
              filters:
                - AddRequestHeader=Origin, http://localhost:4200

            - id: app
              uri: ${APP_URL:http://localhost:8080}
              predicates:
                - Path=/**
              filters:
                - AddRequestHeader=Origin, http://localhost:4200
logging:
  level:
    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: TRACE