server:
  port: 8081
spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
          routes:
            - id: services
              uri: ${BACKEND_URL:http://localhost:8080}
              predicates:
                - Path=/services/api/**

            - id: app-assets
              uri: ${APP_URL:http://localhost:8080}
              predicates:
                - Path=/assets/**

            - id: app
              uri: ${APP_URL:http://localhost:8080}
              predicates:
                - Path=/**
logging:
  level:
    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: TRACE